name: ttcanlaysis_new

dependencies:
    - python=3.7
    - geopandas=0.4.1
    - ipython=7.8.0
    - jupyter=1.0.0
    - matplotlib=3.1.2
    - numpy=1.16.5
    - pandas=0.24.2
    - plotly=4.2.1
    - requests=2.21.0
    - pip:
        - git+https://github.com/x249wang/pyopendatato.git
